apiVersion: "v1"
kind: "Service"
metadata:
  name: "ylz-boilerplate-svc-service"
  namespace: "default"
  labels:
    app: "ylz-boilerplate-svc"
spec:
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3000
  selector:
    app: "ylz-boilerplate-svc"
  type: "LoadBalancer"
  loadBalancerIP: ""
